Add maybe_unused to ranges and nodiscard to start_range.
NVIDIA/NVTX pull request #61
Opened 2022-10-06 19:22 UTC by jrhemstad

Some compilers issues spurious warnings about unused variables for
instances of scoped_range and unique_range. Use [[maybe_unused]] when available
to silence these warnings.

Likewise, added `[[nodiscard]]` when available to `start_range()` to issue a warning
if a user accidently forgets to store the result of `start_range()`. It is not possible to correctly
use `start_range()` without using the result to call `end_range()`.

2023-04-20 11:20 UTC, jrhemstad commented
Hey @jcohen-nvidia would you mind reviewing this so we can get it merged?

2024-11-06 22:33 UTC, evanramos-nvidia requested changes

2024-11-06 22:33 UTC, evanramos-nvidia commented on c/include/nvtx3/nvtx3.hpp
> +  constexpr domain() noexcept {}
This `constexpr` depends on C++11, and will also generate warnings on older versions of MSVC.

2024-11-06 22:33 UTC, evanramos-nvidia commented on c/include/nvtx3/nvtx3.hpp
> +#else
These need preprocessor checks for the C++ language version that implements these attributes, and we could also benefit from adding compiler-specific alternatives for broader support.

2024-12-13 21:49 UTC, evanramos-nvidia commented on c/include/nvtx3/nvtx3.hpp
> +  constexpr domain() noexcept {}
Nevermind this point, I see we already use `constexpr` constructors throughout the file.

2024-12-17 17:30 UTC, merged